services:
  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - '16686:16686'  # UI
      - '4317:4317'    # OTLP gRPC
      - '4318:4318'    # OTLP HTTP
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
